
site_name: 'SnpEff & SnpSift'
site_description: 'SnpEff and SnpSift'
site_author: 'Pablo Cingolani'
copyright: 'Pablo Cingolani'
repo_name: 'SnpEff'

repo_url: 'https://github.com/pcingola/SnpEff'
edit_uri: ''

docs_dir: 'src/docs'
site_dir: 'site'

extra_css:
  - 'stylesheets/extra.css'

theme:
  name: material
  features:
      - navigation.tabs
      - navigation.sections
      - search.highlight
      - search.suggest
      - toc.integrate
      - content.tabs.link
      - content.code.annotate
      - content.code.copy
  palette:
    scheme: slate
    primary: default
    # accent: indigo

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: 'http://www.linkedin.com/in/pablocingolani'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/pcingola/SnpEff'

nav:
  - Home:
     - Home: index.md
     - Usage examples: examples.md
     - License: license.md
  - SnpEff:
     - Introduction: snpeff/introduction.md
     - Running SnpEff: snpeff/running.md
     - Commands &amp; command line options: snpeff/commandline.md
     - Input &amp; output files: snpeff/inputoutput.md
     - Cancer samples: snpeff/cansersamples.md
     - Additional annotations: snpeff/additionalann.md
     - Output summary files: snpeff/outputsummary.md
     - Troubleshooting: snpeff/troubleshooting.md
     - Building databases: snpeff/build_db.md
     - Build databses. GTF / GFF details: snpeff/build_db_gff_gtf.md
     - Building databases. Regulatory and Non-coding: snpeff/build_reg.md
     - Building databases. PDB and AlphaFold: snpeff/build_pdb.md
     - Integration. GATK and Galaxy: snpeff/integration.md
     - Commands and utilities: snpeff/commands.md
     - Human Genomes: snpeff/human_genomes.md
     - Frequently Asked Questions: snpeff/faq.md
  - SnpSift:
     - Introduction: snpsift/introduction.md
     - SnpSift Filter: snpsift/filter.md
     - SnpSift Annotate: snpsift/annotate.md
     - SnpSift CaseControl: snpsift/casecontrol.md
     - SnpSift Intervals: snpsift/intervals.md
     - SnpSift Intervals Index: snpsift/intervalsindex.md
     - SnpSift Join: snpsift/join.md
     - SnpSift RmRefGen: snpsift/rmrefgen.md
     - SnpSift TsTv: snpsift/tstv.md
     - SnpSift Extract Fields: snpsift/extractfields.md
     - SnpSift Variant Type: snpsift/varianttype.md
     - SnpSift GWAS Catalog: snpsift/gwascatalog.md
     - SnpSift dbNSFP: snpsift/dbnsfp.md
     - SnpSift Split: snpsift/split.md
     - SnpSift PhastCons: snpsift/phastcons.md
     - SnpSift Concordance: snpsift/concordance.md
     - SnpSift Private: snpsift/private.md
     - SnpSift Vcf2Tped: snpsift/vcf2ped.md
     - SnpSift Intersect: snpsift/intersect.md
     - SnpSift RmInfo: snpsift/rminfo.md
     - SnpSift GeneSets: snpsift/genesets.md
     - SnpSift GT: snpsift/gt.md
     - SnpSift VcfCheck: snpsift/vcfcheck.md
     - Frequently asked questions: snpsift/faq.md
  - 'Download & Install':
     - Download and install: download.md
  - 'Examples':
     - Examples: examples.md
  - About:
     - About: about.md
     - Help and Bugs: help.md
     - In Memory: xiangyi_lu_donate.md
